spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_management
    username: admin
    password: 6h5K,oE5;9_J
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql
